name: Build/release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2.1.0
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install rpm
      - run: yarn --frozen-lockfile
      - run: yarn dist
      - name: Upload release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
