name: Build/release

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.1.0
      - run: |
          apt update && apt upgrade -y && apt install -y --no-install-recommends git jq curl wget binutils make libopenjp2-tools rpm bsdtar && \
          NVM_LATEST_VER=$(curl -s https://api.github.com/repos/nvm-sh/nvm/releases/latest | jq -r ".name") && \
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_LATEST_VER/install.sh | bash && \
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install node && \
          nvm install-latest-npm && \
          nvm alias default node && \
          npm update -g && \
          npm i -g yarn
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.5.0
        with:
          github_token: ${{ secrets.github_token }}
          build_script_name: 'pack'
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
