name: Build/release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2.1.0
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install rpm
      - run: yarn --frozen-lockfile
      - run: yarn dist
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      - name: Upload release
        uses: svenstaro/upload-release-action@1.0.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          file_glob: true
