name: Build/release

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.1.0
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.5.0
        with:
          github_token: ${{ secrets.github_token }}
          args: "--windows --linux"
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
